(function() {

	rates = new ROCK.ExchangeRates("GBP");

	rates.set("USD", "US Dollar");
	rates.set("EUR", "Euro");
	rates.set("GBP", "British Pound");
	rates.set("INR", "Indian Rupee");
	rates.set("AUD", "Australian Dollars");
	rates.set("JPY", "Japanese Yen");
	rates.set("CHF", "Swiss Franc");
	rates.set("HKD", "Hong Kong Dollar");
	rates.set("ARS", "Argentine Peso");
	rates.set("ALL", "Albanian Lek");
	rates.set("DZD", "Algerian Dinar");
	rates.set("AOA", "Angolan Kwanza");
	rates.set("AMD", "Armenian Dram");
	rates.set("AWG", "Aruban Florin");
	rates.set("AZN", "Azerbaijani Manat");
	rates.set("BSD", "Bahamian Dollar");
	rates.set("BHD", "Bahraini Dinar");
	rates.set("BDT", "Bangladeshi Taka");
	rates.set("BBD", "Barbadian Dollar");
	rates.set("BYR", "Belarusian Ruble");
	rates.set("BZD", "Belize Dollar");
	rates.set("BMD", "Bermudan Dollar");
	rates.set("BTN", "Bhutanese Ngultrum");
	rates.set("BTC", "Bitcoin");
	rates.set("BOB", "Bolivian Boliviano");
	rates.set("BAM", "Bosnia-Herzegovina Convertible Mark");
	rates.set("BWP", "Botswanan Pula");
	rates.set("BRL", "Brazilian Real");
	rates.set("BND", "Brunei Dollar");
	rates.set("BGN", "Bulgarian Lev");
	rates.set("BIF", "Burundian Franc");
	rates.set("KHR", "Cambodian Riel");
	rates.set("CAD", "Canadian Dollar");
	rates.set("CVE", "Cape Verdean Escudo");
	rates.set("KYD", "Cayman Islands Dollar");
	rates.set("XOF", "CFA Franc BCEAO");
	rates.set("XAF", "CFA Franc BEAC");
	rates.set("XPF", "CFP Franc");
	rates.set("CLP", "Chilean Peso");
	rates.set("CNY", "Chinese Yuan");
	rates.set("COP", "Colombian Peso");
	rates.set("KMF", "Comorian Franc");
	rates.set("CDF", "Congolese Franc");
	rates.set("CRC", "Costa Rican Colón");
	rates.set("HRK", "Croatian Kuna");
	rates.set("CZK", "Czech Republic Koruna");
	rates.set("DKK", "Danish Krone");
	rates.set("DJF", "Djiboutian Franc");
	rates.set("DOP", "Dominican Peso");
	rates.set("XCD", "East Caribbean Dollar");
	rates.set("EGP", "Egyptian Pound");
	rates.set("ERN", "Eritrean Nakfa");
	rates.set("ETB", "Ethiopian Birr");
	rates.set("FKP", "Falkland Islands Pound");
	rates.set("FJD", "Fijian Dollar");
	rates.set("GMD", "Gambian Dalasi");
	rates.set("GEL", "Georgian Lari");
	rates.set("GHS", "Ghanaian Cedi");
	rates.set("GIP", "Gibraltar Pound");
	rates.set("GTQ", "Guatemalan Quetzal");
	rates.set("GNF", "Guinean Franc");
	rates.set("GYD", "Guyanaese Dollar");
	rates.set("HTG", "Haitian Gourde");
	rates.set("HNL", "Honduran Lempira");
	rates.set("HUF", "Hungarian Forint");
	rates.set("ISK", "Icelandic Króna");
	rates.set("IDR", "Indonesian Rupiah");
	rates.set("IRR", "Iranian Rial");
	rates.set("IQD", "Iraqi Dinar");
	rates.set("ILS", "Israeli New Sheqel");
	rates.set("ITL", "Italian Lira");
	rates.set("JMD", "Jamaican Dollar");
	rates.set("JOD", "Jordanian Dinar");
	rates.set("KZT", "Kazakhstani Tenge");
	rates.set("KES", "Kenyan Shilling");
	rates.set("KWD", "Kuwaiti Dinar");
	rates.set("KGS", "Kyrgystani Som");
	rates.set("LAK", "Laotian Kip");
	rates.set("LVL", "Latvian Lats");
	rates.set("LBP", "Lebanese Pound");
	rates.set("LSL", "Lesotho Loti");
	rates.set("LRD", "Liberian Dollar");
	rates.set("LYD", "Libyan Dinar");
	rates.set("LTL", "Lithuanian Litas");
	rates.set("MOP", "Macanese Pataca");
	rates.set("MKD", "Macedonian Denar");
	rates.set("MGA", "Malagasy Ariary");
	rates.set("MWK", "Malawian Kwacha");
	rates.set("MYR", "Malaysian Ringgit");
	rates.set("MVR", "Maldivian Rufiyaa");
	rates.set("MRO", "Mauritanian Ouguiya");
	rates.set("MUR", "Mauritian Rupee");
	rates.set("MXN", "Mexican Peso");
	rates.set("MDL", "Moldovan Leu");
	rates.set("MNT", "Mongolian Tugrik");
	rates.set("MAD", "Moroccan Dirham");
	rates.set("MMK", "Myanmar Kyat");
	rates.set("NAD", "Namibian Dollar");
	rates.set("NPR", "Nepalese Rupee");
	rates.set("ANG", "Netherlands Antillean Guilder");
	rates.set("TWD", "New Taiwan Dollar");
	rates.set("NZD", "New Zealand Dollar");
	rates.set("NIO", "Nicaraguan Córdoba");
	rates.set("NGN", "Nigerian Naira");
	rates.set("KPW", "North Korean Won");
	rates.set("NOK", "Norwegian Krone");
	rates.set("OMR", "Omani Rial");
	rates.set("PKR", "Pakistani Rupee");
	rates.set("PAB", "Panamanian Balboa");
	rates.set("PGK", "Papua New Guinean Kina");
	rates.set("PYG", "Paraguayan Guarani");
	rates.set("PEN", "Peruvian Nuevo Sol");
	rates.set("PHP", "Philippine Peso");
	rates.set("PLN", "Polish Zloty");
	rates.set("QAR", "Qatari Rial");
	rates.set("RON", "Romanian Leu");
	rates.set("RUB", "Russian Ruble");
	rates.set("RWF", "Rwandan Franc");
	rates.set("SHP", "Saint Helena Pound");
	rates.set("SVC", "Salvadoran Colón");
	rates.set("WST", "Samoan Tala");
	rates.set("SAR", "Saudi Riyal");
	rates.set("RSD", "Serbian Dinar");
	rates.set("SCR", "Seychellois Rupee");
	rates.set("SLL", "Sierra Leonean Leone");
	rates.set("SGD", "Singapore Dollar");
	rates.set("SBD", "Solomon Islands Dollar");
	rates.set("SOS", "Somali Shilling");
	rates.set("ZAR", "South African Rand");
	rates.set("KRW", "South Korean Won");
	rates.set("XDR", "Special Drawing Rights");
	rates.set("LKR", "Sri Lankan Rupee");
	rates.set("SDG", "Sudanese Pound");
	rates.set("SRD", "Surinamese Dollar");
	rates.set("SZL", "Swazi Lilangeni");
	rates.set("SEK", "Swedish Krona");
	rates.set("SYP", "Syrian Pound");
	rates.set("STD", "São Tomé and Príncipe Dobra");
	rates.set("TJS", "Tajikistani Somoni");
	rates.set("TZS", "Tanzanian Shilling");
	rates.set("THB", "Thai Baht");
	rates.set("TOP", "Tongan Paʻanga");
	rates.set("TTD", "Trinidad and Tobago Dollar");
	rates.set("TND", "Tunisian Dinar");
	rates.set("TRY", "Turkish Lira");
	rates.set("TMT", "Turkmenistani Manat");
	rates.set("UGX", "Ugandan Shilling");
	rates.set("UAH", "Ukrainian Hryvnia");
	rates.set("AED", "United Arab Emirates Dirham");
	rates.set("UYU", "Uruguayan Peso");
	rates.set("UZS", "Uzbekistan Som");
	rates.set("VUV", "Vanuatu Vatu");
	rates.set("VEF", "Venezuelan Bolívar");
	rates.set("VND", "Vietnamese Dong");
	rates.set("YER", "Yemeni Rial");
	rates.set("ZMK", "Zambian Kwacha");
	//rates.set("GRD", "Greek Drachma");
	//rates.set("EEK", "Estonian Kroon");
	//rates.set("CUC", "Cuban Convertible Peso");
	//rates.set("AFA", "Afghan Afghani");
	//rates.set("BEF", "Belgian Franc");
	//rates.set("DEM", "German Mark");
	//rates.set("MZM", "Mozambican Metical");
	//rates.set("SKK", "Slovak Koruna");

})();